# Generated by Django 4.2 on 2023-05-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_team_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='profile_pic',
            field=models.ImageField(blank=True, default='avatar/avatar-11.jpg', null=True, upload_to='profile_pics/%Y/%m/%d/'),
        ),
    ]
