# Generated by Django 4.2 on 2023-05-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='car_photo',
            field=models.ImageField(upload_to='car_photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='car_photo1',
            field=models.ImageField(blank=True, upload_to='car_photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='car_photo2',
            field=models.ImageField(blank=True, upload_to='car_photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='car_photo3',
            field=models.ImageField(blank=True, upload_to='car_photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='car_photo4',
            field=models.ImageField(blank=True, upload_to='car_photos/%Y/%m/%d'),
        ),
    ]
